[package]
name = "drone"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"

[[bin]]
bench = false
name = "drone"
path = "./src/main.rs"
test = false

[[bin]]
bench = false
name = "esp-ikarus"
path = "./src/esp-ikarus/main.rs"
test = false

[dependencies]
# for more networking protocol support see https://crates.io/crates/edge-net
bt-hci = "0.6.0"
critical-section = "1.2.0"
embassy-executor = { version = "0.9.1", features = ["log"] }
embassy-net = { version = "0.7.1", features = [
  "dhcpv4",
  "log",
  "medium-ethernet",
  "tcp",
  "udp",
] }
embassy-time = { version = "0.5.0", features = ["log"] }
embedded-hal = "1.0.0"
embedded-io = "0.7.1"
embedded-io-async = "0.7.0"
esp-alloc = "0.9.0"
esp-bootloader-esp-idf = { version = "0.4.0", features = ["esp32c6", "log-04"] }
esp-hal = { version = "1.0.0", features = ["esp32c6", "log-04", "unstable"] }
esp-println = { version = "0.16.1", features = ["esp32c6", "log-04"] }
esp-radio = { version = "0.17.0", features = [
  "ble",
  "coex",
  "esp-alloc",
  "esp32c6",
  "log-04",
  "smoltcp",
  "unstable",
  "wifi",
] }
esp-rtos = { version = "0.2.0", features = [
  "embassy",
  "esp-alloc",
  "esp-radio",
  "esp32c6",
  "log-04",
] }
log = "0.4.27"
static_cell = "2.1.1"
trouble-host = { version = "0.5.0", features = ["gatt"] }

[profile.dev]
# Rust debug is too slow.
# For debug builds always builds with some optimization
opt-level = "s"

[profile.release]
opt-level = "s"
debug = 2
debug-assertions = false
overflow-checks = false
lto = "fat"
incremental = false
codegen-units = 1  # LLVM can perform better optimizations using a single thread
